# Generated by Django 2.2.5 on 2019-09-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Piet Klaasen', max_length=100)),
                ('emailadress', models.EmailField(default='Email niet bekend', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Boer Henk', max_length=100)),
                ('Age', models.PositiveSmallIntegerField()),
                ('Farm_name', models.CharField(default='Farmerama', max_length=100)),
                ('emailadress', models.EmailField(default='Email niet bekend', max_length=254)),
                ('tel_nr', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
