# Generated by Django 2.2.5 on 2019-09-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='Age',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='tel_nr',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
