# Generated by Django 2.2.5 on 2019-09-30 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0002_auto_20190930_2007'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer',
        ),
    ]
