# Generated by Django 2.2.5 on 2019-10-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0003_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='slug',
            field=models.SlugField(default='profile'),
        ),
    ]
