# Generated by Django 2.2.5 on 2019-10-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0004_farmer_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer',
            old_name='Name',
            new_name='First_Name',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='slug',
        ),
        migrations.AddField(
            model_name='farmer',
            name='Address',
            field=models.CharField(default='Niet bekend', max_length=100),
        ),
        migrations.AddField(
            model_name='farmer',
            name='Last_Name',
            field=models.CharField(default='Haroldsen', max_length=100),
        ),
    ]
