# Generated by Django 2.2.6 on 2020-01-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='orderItemCode',
            field=models.IntegerField(default=0),
        ),
    ]
