# Generated by Django 2.0.3 on 2019-12-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_cart', '0005_auto_20191201_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
