# Generated by Django 2.2.6 on 2020-01-06 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_cart', '0018_auto_20200106_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermanager',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='product_cart.OrderItem'),
        ),
        migrations.AlterField(
            model_name='ordermanager',
            name='orders',
            field=models.ManyToManyField(to='product_cart.Order'),
        ),
    ]
