# Generated by Django 2.2.6 on 2020-01-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_cart', '0020_auto_20200106_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='product_cart.OrderItem'),
        ),
        migrations.DeleteModel(
            name='Ordermanager',
        ),
    ]
