# Generated by Django 2.0.3 on 2019-12-01 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
