# Generated by Django 2.2.5 on 2020-01-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20200106_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(choices=[('artichoke', 'artichoke'), ('aubergine', 'aubergine'), ('asparagus', 'asparagus'), ('broccoflower', 'broccoflower'), ('broccoli', 'broccoli'), ('brussels sprouts', 'brussels sprouts'), ('cabbage', 'cabbage'), ('cauliflower', 'cauliflower'), ('celery', 'celery'), ('endive', 'endive'), ('bok choy', 'bok choy'), ('kale', 'kale'), ('mustard greens', 'mustard greens'), ('spinach', 'spinach'), ('lettuce', 'lettuce'), ('arugula', 'arugula'), ('mushrooms', 'mushrooms'), ('Mais', 'Mais'), ('wheat', 'wheat'), ('radicchio', 'radicchio'), ('rhubarb', 'rhubarb'), ('corn', 'corn'), ('topinambur', 'topinambur'), ('tat soi', 'tat soi'), ('tomato', 'tomato'), ('alfalfa', 'alfalfa'), ('azuki beans', 'azuki beans'), ('black beans', 'black beans'), ('bean sprouts', 'bean sprouts'), ('black-eyed peas', 'black-eyed peas'), ('green beans', 'green beans'), ('kidney beans', 'kidney beans'), ('lentils', 'lentils'), ('peanuts', 'peanuts'), ('soy beans', 'soy beans'), ('peas', 'peas'), ('anise', 'anise'), ('basil', 'basil'), ('caraway', 'caraway'), ('coriander', 'coriander'), ('chamomile', 'chamomile'), ('dill', 'dill'), ('fennel', 'fennel'), ('lavender', 'lavender'), ('Cymbopogon', 'Cymbopogon'), ('marjoram', 'marjoram'), ('oregano', 'oregano'), ('parsley', 'parsley'), ('rosemary', 'rosemary'), ('sage', 'sage'), ('thyme', 'thyme'), ('Chives', 'Chives'), ('Garlic', 'Garlic'), ('Leek', 'Leek'), ('onion', 'onion'), ('shallot', 'shallot'), ('scallion', 'scallion'), ('bell pepper', 'bell pepper'), ('Jalapeño', 'Jalapeño'), ('Habanero', 'Habanero'), ('Paprika', 'Paprika'), ('Tabasco pepper', 'Tabasco pepper'), ('Cayenne pepper', 'Cayenne pepper'), ('beetroot', 'beetroot'), ('carrot', 'carrot'), ('celeriac', 'celeriac'), ('corms', 'corms'), ('ginger', 'ginger'), ('parsnip', 'parsnip'), ('rutabaga', 'rutabaga'), ('radish', 'radish'), ('wasabi', 'wasabi'), ('potato', 'potato'), ('sweet potato', 'sweet potato'), ('yam', 'yam'), ('turnip', 'turnip'), ('Açaí', 'Açaí'), ('Akee', 'Akee'), ('Apple', 'Apple'), ('Apricot', 'Apricot'), ('Avocado', 'Avocado'), ('Banana', 'Banana'), ('Blackberry', 'Blackberry'), ('Blackcurrant', 'Blackcurrant'), ('Blueberry', 'Blueberry'), ('Crab apple', 'Crab apple'), ('Cherry', 'Cherry'), ('Coconut', 'Coconut'), ('Cranberry', 'Cranberry'), ('Date', 'Date'), ('Dragonfruit', 'Dragonfruit'), ('Grape', 'Grape'), ('Grapefruit', 'Grapefruit'), ('Guava', 'Guava'), ('Kiwifruit', 'Kiwifruit'), ('Lemon', 'Lemon'), ('Lime', 'Lime'), ('Lychee', 'Lychee'), ('Mango', 'Mango'), ('Cataloupe Melon', 'Cataloupe Melon'), ('Watermelon', 'Watermelon'), ('Honeydew Melon', 'Honeydew Melon'), ('Nectarine', 'Nectarine'), ('Blood orange', 'Blood orange'), ('Mandarine', 'Mandarine'), ('Clementine Orange', 'Clementine Orange'), ('Papaya', 'Papaya'), ('Passionfruit', 'Passionfruit'), ('Peach', 'Peach'), ('Pear', 'Pear'), ('Persimmon', 'Persimmon'), ('Plantain', 'Plantain'), ('Prune', 'Prune'), ('Pineapple', 'Pineapple'), ('Plumcot', 'Plumcot'), ('Pomegranate', 'Pomegranate'), ('Pomelo', 'Pomelo'), ('Raspberry', 'Raspberry'), ('Redcurrant', 'Redcurrant'), ('Strawberry', 'Strawberry'), ('White currant', 'White currant')], default='artichoke', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(),
        ),
    ]
