# Generated by Django 2.2.7 on 2019-12-01 15:36

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_auto_20191201_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_picture',
            field=smartfields.fields.ImageField(blank=True, upload_to='images/'),
        ),
    ]
