# Generated by Django 2.2.5 on 2019-12-19 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_auto_20191202_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(choices=[(1, 'poor'), (2, 'below average'), (3, 'average'), (4, 'above average'), (5, 'good')])),
                ('review_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.Product')),
            ],
        ),
    ]
