# Generated by Django 2.0.3 on 2019-12-15 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_auto_20191202_1245'),
        ('user_profile', '0004_remove_product_quantity'),
    ]

    operations = [
    ]
