# Generated by Django 2.2.5 on 2019-12-19 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='productReview',
        ),
    ]
