# Generated by Django 2.2.5 on 2019-12-16 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
        migrations.AddField(
            model_name='review',
            name='product_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user_profile.Product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='grade',
            field=models.IntegerField(),
        ),
    ]
