# Generated by Django 2.2.5 on 2019-12-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('fullname', models.CharField(default='ome henk', max_length=44, null=True)),
                ('address', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=2)),
                ('province', models.CharField(max_length=100)),
                ('email', models.EmailField(default='farmer@farmer.nl', max_length=30)),
                ('company_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=10)),
                ('products', models.CharField(max_length=200)),
            ],
        ),
    ]
