# Generated by Django 2.2.5 on 2019-12-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='fullname',
            field=models.CharField(default='ome henk', max_length=44),
        ),
    ]
