# Generated by Django 2.2.7 on 2019-11-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
