# Generated by Django 2.2.7 on 2019-11-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_page', '0004_auto_20191112_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='name',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
