# Generated by Django 2.0.3 on 2019-11-25 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_page', '0003_auto_20191111_1152'),
        ('farmer_page', '0005_auto_20191112_1514'),
    ]

    operations = [
    ]
