# Generated by Django 2.2.5 on 2019-11-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_page', '0006_auto_20191125_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='email',
            field=models.CharField(default='farmer@farmer.nl', max_length=30),
        ),
    ]
