# Generated by Django 2.2.5 on 2019-12-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_page', '0006_auto_20191125_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='email',
            field=models.EmailField(default='fbaba@gmail.com', max_length=30),
        ),
    ]
