# Generated by Django 2.2.5 on 2019-12-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_page', '0007_farmer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='email',
            field=models.EmailField(default='farmer@farmer.nl', max_length=30),
        ),
    ]
