# Generated by Django 2.2.5 on 2019-12-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_page', '0007_farmer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='fullname',
            field=models.CharField(default='ome henk', max_length=44),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='email',
            field=models.EmailField(default='fbaba@gmail.com', max_length=30),
        ),
    ]
