# Generated by Django 2.2.5 on 2019-12-29 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_page', '0009_auto_20191209_1238'),
        ('farmer_page', '0008_auto_20191209_1213'),
    ]

    operations = [
    ]
