# Generated by Django 2.2.5 on 2019-12-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_page', '0010_merge_20191229_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='farmerReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_title', models.CharField(max_length=30)),
                ('review_message', models.CharField(max_length=200)),
                ('review_farmer', models.IntegerField()),
            ],
        ),
    ]
